Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/contact'
  # get 'visits/index'
  # get 'visits/show'
  # get 'visits/new'
  # get 'visits/edit'
  # get 'visits/create'
  # get 'visits/update'
  # get 'visits/destroy'
  # get 'patients/index'
  # get 'patients/show'
  # get 'patients/new'
  # get 'patients/edit'
  # get 'patients/create'
  # get 'patients/update'
  # get 'patients/destroy'
  # get 'doctors/index'
  # get 'doctors/show'
  # get 'doctors/new'
  # get 'doctors/edit'
  # get 'doctors/create'
  # get 'doctors/update'
  # get 'doctors/destroy'
  # get 'doctor/index'
  # get 'doctor/show'
  # get 'doctor/new'
  # get 'doctor/edit'
  # get 'doctor/create'
  # get 'doctor/update'
  # get 'doctor/destroy'

  root 'static_pages#home'
  resources :patients
  resources :doctors
  resources :visits
end
